FROM nvidia/cuda:11.4.2-runtime-ubuntu20.04

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics
LABEL maintainer="Jonas Frey" mail="jonfrey@ethz.ch"

SHELL ["/bin/bash", "--login", "-c"]

# To avoid tzdata asking for geographic location...
ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_frontend noninteractive

RUN apt-get -y update
RUN apt-get install -y git wget vim
RUN apt-get -y install python3-pip
RUN pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
RUN pip3 install open3d
RUN pip3 install vedo
RUN pip3 install trimesh
RUN pip3 install cython
RUN pip3 install scikit-image
# For open3D (needs the noninterative keywork)
RUN apt-get install ffmpeg libsm6 libxext6  -y

# Pyembree
RUN cd /home && git clone https://github.com/scopatz/pyembree.git
RUN cd /home && wget https://github.com/embree/embree/releases/download/v2.17.7/embree-2.17.7.x86_64.linux.tar.gz
RUN cd /home && tar -xf embree-2.17.7.x86_64.linux.tar.gz && source embree-2.17.7.x86_64.linux/embree-vars.sh && cd /home/pyembree && pip3 install -e .
RUN echo "source /home/embree-2.17.7.x86_64.linux/embree-vars.sh" >> /root/.bashrc

# Random number -> always builds.
ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache 
COPY build_script_tar.sh /home/build_script_tar.sh 
COPY ./isaac.tar /home/
RUN chmod +x /home/build_script_tar.sh && /home/build_script_tar.sh

# Clean up
RUN rm -r -f /home/isaac/*
RUN rm /home/build_script_tar.sh
RUN rm /home/isaac.tar